### ISSUE TITLE
Ruby version in repo title

### ISSUE THREAD

**Issue by Mehonoshin** [nbulaj/ruby-chromedriver#2]
Please fix it to be `2.*`, as you did in README.
I've been waiting for 2.5 support for a long time :)

**Comment by nbulaj** [comment]
Thank you @Mehonoshin, fixed! :) Feel free to ping me if something wrong with the package or it need to be updated :+1:

**Comment by Mehonoshin** [comment]
🎉 🎉 🎉 🎉 🎉 
Sure, I will
